# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
