# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_auto_20170330_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='sold_in',
            field=models.TextField(default='1 lb', max_length=20),
            preserve_default=False,
        ),
    ]
